import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  ActivityIndicator,
  Alert,
  ScrollView,
  TouchableOpacity,
  Share,
  Platform,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { UsersAPI, InvitesAPI } from '../api';
import { readStoredInviteCode, writeStoredInviteCode } from '../lib/storage';
import { useTheme } from '../theme';

export default function InviteScreen({ navigation }: any) {
  const { colors } = useTheme();
  const [loading, setLoading] = React.useState(true);
  const [inviteCode, setInviteCode] = React.useState<string | null>(null);

  const ensureInviteCode = React.useCallback(
    async (viewerId?: string | null): Promise<string | null> => {
      const normalizedId = typeof viewerId === 'string' ? viewerId.trim() : '';
      if (normalizedId) {
        const cached = await readStoredInviteCode(normalizedId);
        if (cached) {
          return cached;
        }
      }

      // Try to list existing invites first
      try {
        if (InvitesAPI.listInvites) {
          const existing = await InvitesAPI.listInvites();
          const existingCode = UsersAPI.findInviteCode?.(existing) ?? null;
          if (existingCode) {
            if (normalizedId) {
              await writeStoredInviteCode(normalizedId, existingCode);
            }
            return existingCode;
          }
        }
      } catch (error: any) {
        // Silently continue if listing fails - we'll try to create
        const errorMsg = error?.message || String(error);
        console.log('[Invites] Could not list invites, will try to create:', errorMsg);
      }

      // Try to create a new invite code
      try {
        const payload = await InvitesAPI.createInvite(10);
        const code = UsersAPI.findInviteCode?.(payload) ?? null;
        const fallback =
          payload && typeof payload === 'object' && 'code' in (payload as any)
            ? String((payload as any).code)
            : null;
        const normalizedCode = code || (fallback && fallback.trim().length > 0 ? fallback.trim() : null);
        if (normalizedCode && normalizedId) {
          await writeStoredInviteCode(normalizedId, normalizedCode);
        }
        return normalizedCode ?? null;
      } catch (error: any) {
        const errorMsg = error?.message || String(error);

        if (errorMsg.includes('INVITE_CREATE_FORBIDDEN') || errorMsg.includes('403')) {
          console.log('[Invites] User cannot create invites - may be auto-generated by backend');
        } else if (errorMsg.includes('404')) {
          console.log('[Invites] Invite endpoints not found - backend may not support user invites yet');
        } else {
          console.warn('[Invites] Unexpected error:', errorMsg);
        }

        return null;
      }
    },
    []
  );

  const loadInviteCode = React.useCallback(async () => {
    setLoading(true);
    try {
      const data = await UsersAPI.me();
      const normalizedId =
        data && typeof (data as any).id === 'string' && (data as any).id.trim().length
          ? (data as any).id.trim()
          : null;
      let normalizedInviteCode =
        data && typeof (data as any).inviteCode === 'string' && (data as any).inviteCode.trim().length
          ? (data as any).inviteCode.trim()
          : null;

      if (!normalizedInviteCode && normalizedId) {
        normalizedInviteCode = await readStoredInviteCode(normalizedId);
      }

      if (!normalizedInviteCode) {
        normalizedInviteCode = await ensureInviteCode(normalizedId);
      }

      setInviteCode(normalizedInviteCode);

      if (normalizedInviteCode && normalizedId) {
        await writeStoredInviteCode(normalizedId, normalizedInviteCode);
      }
    } catch (error: any) {
      console.error('Failed to load invite code:', error);
      Alert.alert('Error', error?.message || 'Unable to load invite code.');
    } finally {
      setLoading(false);
    }
  }, [ensureInviteCode]);

  React.useEffect(() => {
    loadInviteCode();
  }, [loadInviteCode]);

  const handleShare = async () => {
    if (!inviteCode) {
      Alert.alert('No invite code', 'Your invite code is not available yet.');
      return;
    }

    try {
      const message = `Join me on Scoot! Use my invite code: ${inviteCode}`;
      const result = await Share.share({
        message,
        ...(Platform.OS === 'ios' && { url: 'https://apps.apple.com/us/app/scoot-social/id6755162428' }),
      });

      if (result.action === Share.sharedAction) {
        if (result.activityType) {
          // shared with activity type of result.activityType
          console.log('Shared via:', result.activityType);
        } else {
          // shared
          console.log('Invite code shared successfully');
        }
      } else if (result.action === Share.dismissedAction) {
        // dismissed
        console.log('Share dismissed');
      }
    } catch (error: any) {
      console.error('Error sharing invite code:', error);
      Alert.alert('Error', 'Failed to share invite code. Please try again.');
    }
  };

  if (loading) {
    return (
      <View style={[styles.loadingContainer, { backgroundColor: colors.background.primary }]}>
        <ActivityIndicator size="large" color={colors.primary[500]} />
      </View>
    );
  }

  const inviteCodeLabel = inviteCode || 'Not available yet';

  return (
    <SafeAreaView style={[styles.safeArea, { backgroundColor: colors.background.secondary }]} edges={['bottom']}>
      <ScrollView contentContainerStyle={styles.container}>
        <View style={styles.iconContainer}>
          <View style={[styles.iconCircle, { backgroundColor: colors.primary[100] }]}>
            <Ionicons name="person-add" size={48} color={colors.primary[500]} />
          </View>
        </View>

        <Text style={[styles.title, { color: colors.text.primary }]}>Invite Friends</Text>

        <Text style={[styles.description, { color: colors.text.secondary }]}>
          Scoot is more fun with friends. Share your invite code with friends to expand your community on Scoot!
        </Text>

        <View style={styles.codeSection}>
          <Text style={[styles.codeLabel, { color: colors.text.secondary }]}>Your invite code</Text>
          <View
            style={[
              styles.inviteCodeBox,
              {
                backgroundColor: colors.background.elevated,
                borderColor: inviteCode ? colors.primary[300] : colors.border.main,
              },
            ]}
          >
            <Text
              selectable={!!inviteCode}
              style={[
                styles.inviteCodeText,
                { color: inviteCode ? colors.text.primary : colors.text.tertiary },
              ]}
            >
              {inviteCodeLabel}
            </Text>
          </View>
          {inviteCode ? (
            <Text style={[styles.hint, { color: colors.text.tertiary }]}>
              Tap to copy or use the share button below
            </Text>
          ) : (
            <Text style={[styles.hint, { color: colors.text.tertiary }]}>
              Your invite code will appear here once generated by the system
            </Text>
          )}
        </View>

        {inviteCode && (
          <TouchableOpacity
            style={[styles.shareButton, { backgroundColor: colors.primary[500] }]}
            onPress={handleShare}
            activeOpacity={0.8}
          >
            <Ionicons name="share-outline" size={20} color="#fff" style={styles.shareIcon} />
            <Text style={styles.shareButtonText}>Share Invite Code</Text>
          </TouchableOpacity>
        )}
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  loadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  container: {
    padding: 24,
    alignItems: 'center',
    paddingTop: 40,
  },
  iconContainer: {
    marginBottom: 24,
  },
  iconCircle: {
    width: 96,
    height: 96,
    borderRadius: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    marginBottom: 12,
    textAlign: 'center',
  },
  description: {
    fontSize: 16,
    lineHeight: 24,
    textAlign: 'center',
    marginBottom: 40,
    paddingHorizontal: 8,
  },
  codeSection: {
    width: '100%',
    marginBottom: 32,
  },
  codeLabel: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 8,
    textAlign: 'center',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  inviteCodeBox: {
    borderWidth: 2,
    borderStyle: 'dashed',
    borderRadius: 16,
    padding: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  inviteCodeText: {
    fontSize: 32,
    fontWeight: '700',
    letterSpacing: 2,
    textAlign: 'center',
  },
  hint: {
    fontSize: 13,
    textAlign: 'center',
    marginTop: 12,
  },
  shareButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: 12,
    width: '100%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  shareIcon: {
    marginRight: 8,
  },
  shareButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
});
