
import { api } from './client';

/**
 * List user's invite codes
 * Tries multiple endpoint variations to support different backend implementations
 */
export async function listInvites(){
  // Try user-specific endpoint first (most likely for per-user invites)
  try {
    return await api('/me/invites');
  } catch (error: any) {
    const is404 = error?.message?.includes('404');

    if (is404) {
      // Try singular form
      try {
        return await api('/me/invite');
      } catch (singleError: any) {
        if (singleError?.message?.includes('404')) {
          // Finally try global endpoint
          return api('/invites');
        }
        throw singleError;
      }
    }
    throw error;
  }
}

/**
 * Create a new invite code for the current user
 * Tries multiple endpoint variations to support different backend implementations
 */
export async function createInvite(uses = 10){
  const payload = { uses };

  // Try user-specific endpoints first (POST /me/invite or POST /me/invites)
  try {
    return await api('/me/invite', {
      method: 'POST',
      body: JSON.stringify(payload)
    });
  } catch (error: any) {
    const is404 = error?.message?.includes('404');
    const is403 = error?.message?.includes('403');

    if (is404) {
      // Try plural form
      try {
        return await api('/me/invites', {
          method: 'POST',
          body: JSON.stringify(payload)
        });
      } catch (pluralError: any) {
        if (pluralError?.message?.includes('404')) {
          // Finally try global endpoint
          return api('/invites', {
            method: 'POST',
            body: JSON.stringify(payload)
          });
        }
        throw pluralError;
      }
    }

    // If we get 403, it means the endpoint exists but user can't create invites
    // This might mean invites are auto-generated by backend
    if (is403) {
      throw new Error('INVITE_CREATE_FORBIDDEN');
    }

    throw error;
  }
}
